### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by hhkaos** [esri-es/koop-provider-google-drive#1]
- [ ] Be able to load different spreadsheet IDs
- [ ] Format date fields
- [ ] Improve the way to detect latitude and longitude
- [ ] Be able to select a sheet inside the spreadsheet (using params?)
